# PlotTweaks Config

sound-blocking:
  enabled: true
  block-wither-sound: true
  block-end-portal-opening: true


redstone-limiting:
  enabled: true
  message: "Redstone is currently temporally disabled on this Plot"
  enable_bypass_flag: true
  max_redstone_operations_limit: 4096

# ONLY WORKS WITH PAPER
limit-beacon-to-plot: true

